### ISSUE TITLE
Can not be used in Blender 2.79 

### ISSUE THREAD

**Issue by NoviceInDisguise** [samytichadou/FontSelector_blender_addon#1]
Somewhat as expected, Blender 2.79 breaks the addon. It creates the region in the Text Data page, however it is empty.

**Comment by samytichadou** [comment]
Hi, thanks for the feedback, that's weird, i tested the addon on 2.79 extensively two days ago, and no problem so far... which is the exact issue ? the list is empty ? and what happened when you click the refresh button ?

**Comment by NoviceInDisguise** [comment]
I get the region where the addon should display, but there are no elements within it. It's just blank.

**Comment by samytichadou** [comment]
definitely not doing that on windows for me... did you add a font folder in the user prefs ? did you hit the refresh button ? do you have any message concerning the addon in the console ? what os do you use ?

**Comment by NoviceInDisguise** [comment]
Re-installing the latest version of the addon it now shows the buttons etc, refresh works properly as well. Not sure what was causing the bug earlier, but it seems to have been fixed by re-installing.

**Comment by samytichadou** [comment]
perfect ! good to know, if you encounter the issue again, check console for potential drawing errors, i think it came from here, but not idea of the why (just checked the code again...)
