### ISSUE TITLE
Is this available for blender 2.83?

### ISSUE THREAD

**Issue by 3dcinetv** [samytichadou/FontSelector_blender_addon#10]
I saw this addon with pop up options, the screen seemed to be taken from the 2.8x version in Blender.
Is this available for Blender 2.83?

**Comment by karrirasinmaki** [comment]
Seems like this addon is working well on Blender 2.83 but only on VSE. Font selection does not work with 3D objects.

**Comment by samytichadou** [comment]
the addon should work in 2.83, for now, there is some bug with pop up panel (the search doesn't update until you hit enter), otherwise, should be working normally

**Comment by samytichadou** [comment]
Hi sorry for late answer.
v2.x should work fine with 2.8.x and newer.

I just released a [new alpha version for blender 4.2.x](https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1) (extension format), for now it is not on the extension platform, i need some feedbacks on win/mac.

I'm closing this ticket
https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1
