### ISSUE TITLE
Enabling 2.13

### ISSUE THREAD

**Issue by Ingapambi** [samytichadou/FontSelector_blender_addon#11]
With MacOS 11.01, Blender 2.91, IMac Pro Ican't enable 2.13. 2.1 enabled but wouldn't show up in the 
<img width="1670" alt="Screen Shot 2020-12-11 at 3 08 33 AM" src="https://user-images.githubusercontent.com/44510383/101897306-30b48180-3b5f-11eb-85e2-9c736db66ac2.png">
menu.

**Comment by samytichadou** [comment]
sorry for late reply, did you find a solution ? for now i don't really get why this error appears, and about the v2.1, you can enable it through addon ? or only install ? and what doesn't show up in menu ? entire font selector panel ?
cheers !
