### ISSUE TITLE
double font listing in font selection

### ISSUE THREAD

**Issue by MaxTux** [samytichadou/FontSelector_blender_addon#12]
i get this error:

Traceback (most recent call last):
  File "/home/tigro/.config/blender/2.83/scripts/addons/FontSelector_blender_addon-master/operators/check_changes.py", line 38, in execute
    checkDesyncFonts()
  File "/home/tigro/.config/blender/2.83/scripts/addons/FontSelector_blender_addon-master/functions/check_desync_fonts.py", line 30, in checkDesyncFonts
    if scn.sequence_editor.sequences_all is not None:
AttributeError: 'NoneType' object has no attribute 'sequences_all'

location: <unknown location>:-1
![Schermata da 2021-02-16 16-54-14](https://user-images.githubusercontent.com/8472723/108087456-c1d03900-7077-11eb-8895-acc6d1c69a54.png)

**Comment by samytichadou** [comment]
Hi sorry for late answer

I just released a [new alpha version for blender 4.2.x](https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1) (extension format), for now it is not on the extension platform, i need some feedbacks on win/mac.

I'm closing this ticket, feel free to reopen or create a new one if the new version does not work as expected (it is alpha software)
https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1
