### ISSUE TITLE
I have no idea how it works

### ISSUE THREAD

**Issue by BrettByers** [samytichadou/FontSelector_blender_addon#13]
I have it installed and have the fonts folder loaded, I see the fonts to select and yet when i select them nothing happens. any ideas what I'm missing?  [https://gyazo.com/8b907f6c24b8641f623eb534ef221d44](url)

**Comment by samytichadou** [comment]
Hi sorry for late answer

I just released a [new version for blender 4.2.x](https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1) (extension format), this strange bug should be fixed. Can you test if it is ok ? :) thanks !

I'm closing this issue, feel free to reopen and create a new one if new version still have this bug ! 

https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1
