### ISSUE TITLE
Mac OS Compatibility

### ISSUE THREAD

**Issue by Blender-In-The-Grass** [samytichadou/FontSelector_blender_addon#14]
FontSelector works fine on my Mac with Blender 2.9.2, macOS Catalina 10.15.7, IF I select a folder outside the system. Selecting the Library / Fonts folder causes Blender to freeze. I don't know if this is something that can be fixed. If so, great. Until then, I'm building a folder of fonts outside my system to use with Blender. Thanks for all your hard work. It is appreciated.

- Mark Alan Cirino 
   cirino@mcn.org

**Comment by samytichadou** [comment]
Hi sorry for late answer
v2.x had a lot of issues with mac.

I just released a [new version for blender 4.2.x](https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1) (extension format), can you test and post here if it is ok ?
I don't own a mac system to test :) thanks !

https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1

**Comment by samytichadou** [comment]
closing for lack of answer, should work in next version
