### ISSUE TITLE
Problems opening 2.90 in 3.0 which used FontSelector

### ISSUE THREAD

**Issue by lajawi** [samytichadou/FontSelector_blender_addon#15]
If I open a Blender file created in 2.90 which I used the addon in, in 3.0, I get an error on refreshing *and* all text objects are just X'.
I'm using version 2.1.2 of the addon in Blender 3.0.
![The error I get upon refreshig the fonts.](https://user-images.githubusercontent.com/51792807/148698961-40b3901c-37de-4de3-9af0-5d2a7b54c95f.png)

**Comment by samytichadou** [comment]
Hi sorry for late answer

I just released a [new alpha version for blender 4.2.x](https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1) (extension format), should be fixed.
Don't hesitate to test and give feedback, i need some of them from win/mac users ! :) (currently tested on linux)

https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1
