### ISSUE TITLE
Freezing up on macOS

### ISSUE THREAD

**Issue by different55** [samytichadou/FontSelector_blender_addon#16]
Enabled the addon on v3.1 of Blender on macOS, and it instantly started choking up. Snooping around, it seems to be trying to scan my entire home directory and it's not getting very far with that.

**Comment by samytichadou** [comment]
Hi sorry for late answer
v2.x had a lot of issues with mac.
I just released a [new version for blender 4.2.x](https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1) (extension format), can you test and post here if it is ok ?
I don't own a mac system to test :) thanks !
https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1

**Comment by different55** [comment]
Hey, thanks for getting back! Gave it a test run, had a brief and confusing time realizing that alpha 1 is *not* what's currently in the blender_4_2_x_extension branch, updated to alpha 5, and it's working great!

Only issue I'm having is that I'm only realizing now that so many of my fonts are variable fonts and aren't really supported in Blender. When you don't have a super convenient list you can just tap your way through, that's a lot easier to miss!
