### ISSUE TITLE
Some fonts don't show up

### ISSUE THREAD

**Issue by lajawi** [samytichadou/FontSelector_blender_addon#17]
I have the folder path set to `C:\Windows\Fonts\`, meaning all windows installed fonts *should* be recognized by the addon, but some just never show up, not even after refreshing.

**Comment by samytichadou** [comment]
Hi sorry for late answer
The issue could have come from different font type, or from a font user folder which is not taken into account.

I just released a [new alpha version for blender 4.2.x](https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1) (extension format), for now it is not on the extension platform, i need some feedbacks on win/mac. If you own one, don't hesitate to test it ! :)
I'm closing this ticket, feel free to reopen or create a new one if the new version does not work as expected (it is alpha software)
https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1
