### ISSUE TITLE
Rewrite as Blender Extension - *TESTERS NEEDED*

### ISSUE THREAD

**Issue by Kovadon** [samytichadou/FontSelector_blender_addon#18]
Hi, it would be really cool to have FontSelector available on the new extensions platform, any plans?
https://extensions.blender.org/

**Comment by samytichadou** [comment]
Hi sorry for late answer
I just released a [new alpha version for blender 4.2.x](https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1) (extension format), for now it is not on the extension platform, i need some feedbacks on win/mac. If you own one, don't hesitate to test it ! :)
https://github.com/samytichadou/FontSelector_blender_addon/releases/tag/v3_0_0_a1

**Comment by mac4kent** [comment]
Hello @samytichadou I talk with you before about path ~/Library/font/ you did good fixed for Blender 4.2 and up. I do have MacBook Pro M3 Pro and there miss extension for Blender 4.3.1
I can help you through terminal and copy then send you on .txt

**Comment by mac4kent** [comment]
it worked on path fonts.
![image](https://github.com/user-attachments/assets/26e21838-e997-4ce3-94cc-7bc8afc65986)

**Comment by samytichadou** [comment]
> Hello @samytichadou I talk with you before about path ~/Library/font/ you did good fixed for Blender 4.2 and up. I do have MacBook Pro M3 Pro and there miss extension for Blender 4.3.1 I can help you through terminal and copy then send you on .txt

thanks for the proposal, i'll finish the code this week (spare time finally :) ) and get back to you here !

**Comment by samytichadou** [comment]
Here is a beta version to test if anyone uses win or mac, don't hesitate to give feedback ! 
cheers 

https://github.com/samytichadou/FontSelector_blender_addon/releases/download/v3_0_0_b1/font_selector_3_0_0_b1.zip

**Comment by mac4kent** [comment]
Blender 4.2.3 LTE it worked and can show display.
Blender 4.3.1 it worked and can show display. ![image](https://github.com/user-attachments/assets/c7ddfaa9-9968-465a-ad77-1a4b46342114)

and

Blender 4.4.0 it worked path but not display. see picture

 ![image](https://github.com/user-attachments/assets/d62d6d2c-cbad-455d-af09-693470a18e7e)

**Comment by mac4kent** [comment]
Regular, Bold, Italic, Bold/Italic on popmenu it worked.

**Comment by samytichadou** [comment]
> Blender 4.4.0 it worked path but not display. see picture

Thanks for testing. For the v4.4.x, no way to test for now for me, 4.4 seems broken on linux with missing libraries.
But giving it is an alpha release, i'll test again when it hits beta stage.

Did you try the reveal file operator ? it is located in the Font infos part, and should open a finder with the font file selected. This is os dependant, and i couldn't test it for now.

**Comment by mac4kent** [comment]
Yes I saw auto path itself on 
~/Library/Font can read.
 /Volumes/Kent\ Davis\ 2/System/Library/Fonts can read. 
it worked.

Apple Braille have miss part. Because of .TFF
![image](https://github.com/user-attachments/assets/acddaeee-bd16-41cb-9ddb-9b2d0d76b84f)
![image](https://github.com/user-attachments/assets/d50e79ef-2c43-4801-8bb6-f5fb963bd264)

Supplements folder
![image](https://github.com/user-attachments/assets/1544dae4-0c87-437f-b271-3b52fea01ca2)

Apple Color some miss .ttc
![image](https://github.com/user-attachments/assets/fe1e4b03-4356-409e-a798-6bfd8b2fa58c)

**Comment by samytichadou** [comment]
Thanks for taking the time to test ! :)

> Apple Braille have miss part. Because of .TFF

What do you mean by that ? Sorry did not test Braille font, does it behave weirdly with the addon ?

**Comment by mac4kent** [comment]
Yes there have some miss. I can send you my zip of fonts.
https://mega.nz/file/dlkgxRrB#5W6NZVV5kAaMmmppUlnsTUlBQRniahROgvm-Fs8k2qc

**Comment by samytichadou** [comment]
> Yes there have some miss. I can send you my zip of fonts. https://mega.nz/file/dlkgxRrB#5W6NZVV5kAaMmmppUlnsTUlBQRniahROgvm-Fs8k2qc

thanks, and nice catch, there was a problem with the font family getting, i'm updating it :)
![image](https://github.com/user-attachments/assets/c57d9824-0d1d-48a2-aa39-a15195d8ef92)

But unfortunately, blender does not seem to be compliant with braille fonts...

**Comment by mac4kent** [comment]
Oh I seeeeeeeeeeeeeeeee

**Comment by mac4kent** [comment]
Can you work on auto width more room bigger fit the text?

**Comment by samytichadou** [comment]
So you can get the new version here 
https://github.com/samytichadou/FontSelector_blender_addon/releases/download/v3_0_1/font_selector_3_0_1.zip

> Can you work on auto width more room bigger fit the text?

I don't know what you mean by that sorry, can you elaborate ?

**Comment by mac4kent** [comment]
Oh I see that Properties on Fonts Select I notice. Never mind there already support mouse drag width and mouse drag move down height itself support.
I test Blender 4.2.3, 4.3.1 all it worked plus visible can show
![image](https://github.com/user-attachments/assets/12cf49b1-3499-4d64-a0ab-52692ad31bee)

and
Blender 4.4.0 you explain me will become beta then you will take test on Blender 4.4.0 beta later few months later. I understand.

This below picture is very excellent and congratulation good job. I able drag on properties.
![image](https://github.com/user-attachments/assets/8456ca2f-66e7-4921-9019-924399b24361)

**Comment by samytichadou** [comment]
> This below picture is very excellent and congratulation good job. I able drag on properties.
Thanks for the kind words, glad you find the extension useful ! :)

I just uploaded it on blender extension platform :
https://extensions.blender.org/approval-queue/font-selector/

It has yet to be approved, but it is in the process. I'll let this issue open until it is.

**Comment by mac4kent** [comment]
2 different word "Font Selection" and "Font Selector" on your extension.

**Comment by mac4kent** [comment]
Ok NP

**Comment by mac4kent** [comment]
Yes I can see after you send me notification email this here. I able to Font Selection yaaaa ay. All is fine and very excellent.
Very easy. When you do update and I can notice on below and right side of (earth) 4.2.xx) appear itself and I able to update button that is best one. Yaaaa ay.

**Comment by mac4kent** [comment]
See my report a ticket about Blender any number version. https://projects.blender.org/blender/blender/issues/131453#issuecomment-1368329

**Comment by mac4kent** [comment]
Mac can read everything unlimit fonts.
without extension and within extension not matter.
1. (without dot)
2. .ttf
3. .ttc
4. otf
and ETC.
See my youtube for 12 minutes https://youtu.be/jI5-2YKzB6g

**Comment by mac4kent** [comment]
You may see Blender report a ticket.
https://projects.blender.org/blender/blender/issues/131694#issuecomment-1368407

**Comment by mac4kent** [comment]
https://projects.blender.org/blender/blender/issues/131694
https://forum.affinity.serif.com/index.php?/topic/225780-font-something-wrong-on-designer-photo-and-other-for-mac-only/
