### ISSUE TITLE
Add font folder in Add-on Prefs

### ISSUE THREAD

**Issue by LobsterShane** [samytichadou/FontSelector_blender_addon#2]
So I've installed the add-on and in my 'Font'tab it advises me to "addfont folder in add-on preferences'. Don't know what the hell this means. Can you help?

**Comment by samytichadou** [comment]
Hi, you have to indicates folder where fonts are stored on your computer for the addon to work. You do that through the addon user preferences (ctl alt u). Click the + button and setup the folder path. You can check this on the video walkthrough on youtube (link in the wiki)
Tell me if it's good for you !
