### ISSUE TITLE
FontSelector error message

### ISSUE THREAD

**Issue by JDubendorf** [samytichadou/FontSelector_blender_addon#3]
Hello- I just installed Font Selector on the latest Blender build, and am receiving this error message after I define a font folder and attempt to refresh the list.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\fontselector_1_25.py", line 396, in execute
    nfile.write(f.name+" || "+nfpath+' || '+os.path.basename(os.path.dirname(nfpath))+"\n")
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2560' in position 32: character maps to <undefined>

**Comment by samytichadou** [comment]
Hi JDubendorf, i wasn't able to reproduce the error yet, what blender version exactly are you using ? daily build for 2.7X ? And what OS are you using ? windows 10 giving path of the addon ?
