### ISSUE TITLE
Error while refreshing fonts folder

### ISSUE THREAD

**Issue by LuisBurdallo** [samytichadou/FontSelector_blender_addon#6]
Json file is created and the fonts will work only once Blender has been restarted.

Traceback (most recent call last):
File “C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector_blender_addon-master\operators\modal_refresh.py”, line 169, in modal
path, subdir, name = self.font_list[count]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File “C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector_blender_addon-master\operators\modal_refresh.py”, line 206, in modal
self.finish(context)
File “C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector_blender_addon-master\operators\modal_refresh.py”, line 288, in finish
change_list_update()
File “C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector_blender_addon-master\functions\change_list_update.py”, line 17, in change_list_update
avoid_list = avoid_changes_selected()
File “C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector_blender_addon-master\functions\misc_functions.py”, line 107, in avoid_changes_selected
seq = scn.sequence_editor.sequences_all
AttributeError: ‘NoneType’ object has no attribute ‘sequences_all’

location: :-1

**Comment by LuisBurdallo** [comment]
Blender:
============================================

version: 2.80 (sub 74), branch: master, commit date: 2019-06-23 22:45, hash: 9c5d54bfaf48, type: Release
build date: 23/06/2019, 17:05
platform: Windows

**Comment by samytichadou** [comment]
#961d742 should correct the bug, can you try it ?
It was a bug because blender was looking for a video sequence which doesn't exist in a newly created scene

**Comment by LuisBurdallo** [comment]
Thanks a lot. I've replaced the code inside the misc_functions only and I get this error basically at the same refreshing point.

Traceback (most recent call last):
  File "C:\Users\Luis Burdallo\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector\operators\modal_refresh.py", line 184, in modal
    self.json_font_list.append([datafont.name, path, subdir])
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 5: invalid continuation byte

location: <unknown location>:-1

**Comment by samytichadou** [comment]
@LuisBurdallo you can download here from master instead of copy paste piece of code if you want !
ok so 1/2 corrected, i'm gonna take a look at this one

**Comment by LuisBurdallo** [comment]
I know yeah I just didn't find a way to download single files instead of everything again. But I guess it won't take long anyway. Will do next time.

**Comment by samytichadou** [comment]
can you download the addon again and try with "debug toggle" on ? (it is located in the addon preferences)
You can check last font about to be treated before the error in the console and post it here ! i added a few debug infos for it !
(https://github.com/samytichadou/FontSelector_blender_addon/commit/1e244b5ccbf3387272b3e2edee14c6822d083c78)

**Comment by LuisBurdallo** [comment]
583/2250 fonts treated --- Wacamoler Caps FFP.ttf about to be treated
Traceback (most recent call last):
  File "C:\Users\Luis Burdallo\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector_blender_addon-master\operators\modal_refresh.py", line 189, in modal
    self.json_font_list.append([datafont.name, path, subdir])
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 5: invalid continuation byte

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by samytichadou** [comment]
i was able to reproduce the error which comes from this particular font (the name contains a "Ó" which raise the utf error)
this error can happened with other random font, so i'll try to get ride of non utf-8 character of every font before creating the json, but i will not have time since next week, sorry.
For now you can just move the font file to another location to avoid it if you want to use the addon, sorry for the inconvenience ! 
i'll keep you posted !

**Comment by samytichadou** [comment]
https://github.com/samytichadou/FontSelector_blender_addon/commit/09ca259919ae582e8453960a5e60727d87dfe470 should solve the problem, 

Blender basically load fonts which have erratic name (non utf8 compliant) and doesn't give you access to the erratic string afterward (unicodedecodeerror). 
When you try to call this erratic string property (the font name) from the console within blender, it crashes the software. It may be a weird bug, i'll report it

Meanwhile, i took care of the problem by getting id_prop of the erratic font as a string, and extracting the name out of it, not really classy, but it works !

Can you test it ?
If it works for you, i'll make a new release with it !

**Comment by LuisBurdallo** [comment]
Sorry for the late reply mate. It scanned fine but I get this error at the end so fonts don't work until I restart Blender. Another thing is do you think the menu options would be better at the top instead of at the bottom? I find it odd I have to scroll down in order to see the font folders etc... That is just a suggestion. 

Traceback (most recent call last):
  File "C:\Users\Luis Burdallo\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector_blender_addon-master\operators\modal_refresh.py", line 177, in modal
    path, subdir, name = self.font_list[count]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Luis Burdallo\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector_blender_addon-master\operators\modal_refresh.py", line 226, in modal
    self.finish(context)
  File "C:\Users\Luis Burdallo\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector_blender_addon-master\operators\modal_refresh.py", line 311, in finish
    change_list_update()
  File "C:\Users\Luis Burdallo\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector_blender_addon-master\functions\change_list_update.py", line 52, in change_list_update
    seq = scn.sequence_editor.sequences_all
AttributeError: 'NoneType' object has no attribute 'sequences_all'

location: <unknown location>:-1

**Comment by samytichadou** [comment]
Hi, ok i see, another error coming from the handling of a blender project without any sequences in it.
Last commits should correct it (https://github.com/samytichadou/FontSelector_blender_addon/commit/135a53be92b22fea391b4230774b46ea73259311#diff-356ef322cc01c1c2ba09591349c8a0dc)
I wasn't able to reproduce the error, so this is a blind fix, can you test it downloading from master ? 
cheers ! (and thx for your patience ;) )

PS : regarding the filtering options, yep i'm currently using a UI list template from blender python api, but i have to dig more to make it more user friendly, this is planned !

**Comment by LuisBurdallo** [comment]
Thanks, man. I've just installed it and now the refresh icon is missing so I can't test if its solved.

**Comment by samytichadou** [comment]
it should be under the font list, i tried some UI reorganisation :) if not, can you check the console for error ?

**Comment by LuisBurdallo** [comment]
When I activated the addon, the font selection properties was totally empty just the message to refresh without the refresh icon. After a restart, the fonts where there. I just hit refresh again and it all went well. I guess is just that little issue regarding the first installation.

**Comment by samytichadou** [comment]
oh yep it comes from the ui tests, i ll correct it tomorrow, but the auto refresh on startup seems to work now with your fonts ! i ll keep you posted, then make a new release of the addon ! thanks a lot for the reports mate !

**Comment by samytichadou** [comment]
and this should fix it :)
https://github.com/samytichadou/FontSelector_blender_addon/commit/bf7cef0eb98a218e45a0b837d960187fa08fa76c
this issue seems closed, thanks for pointing out these bugs !

**Comment by LuisBurdallo** [comment]
Thanks to you for taking care of the problem.
