### ISSUE TITLE
Latest version of FS doesn't seem to work with 2.79

### ISSUE THREAD

**Issue by RodeyOrg** [samytichadou/FontSelector_blender_addon#7]
I install the addon from the site but when I click on it to add to blender Mac (in the user preferences) it throws an error consistently. Strangely though it seems an older version (1.25) will install correctly.

**Comment by samytichadou** [comment]
Hi, yes there is two answers to this problems :

-first of all, new version of FS (v2x) will are only for Blender 2.8x, if you want to stick with Blender 2.7x, please use the v1.25 ([https://github.com/samytichadou/FontSelector_blender_addon/tree/version1_blender_2_7x])

- when downloading something through github "clone or download" button, github will automatically add a suffix in the name (the branch name) and put a "-" character in it, which is a special character and could prevent Blender to see the addon as installed. You have to get rid of these special characters by hand, i know it is a bummer, but that is how it works for now with this platform... sorry about that

cheers dude, and thanks for using FS ;)
