### ISSUE TITLE
Font won't change for already available texts in projects. Restarting and adding new texts to a new projects seems to work.

### ISSUE THREAD

**Issue by LuisBurdallo** [samytichadou/FontSelector_blender_addon#8]
File “C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector_blender_addon-master\functions\update_functions.py”, line 25, in update_change_font
idx = active.data.fontselector_index
AttributeError: ‘Mesh’ object has no attribute ‘fontselector_index’
File “C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\FontSelector_blender_addon-master\functions\update_functions.py”, line 11, in update_change_font
Font Selector — Settings Loaded

**Comment by samytichadou** [comment]
https://github.com/samytichadou/FontSelector_blender_addon/commit/ea224168f01bc4d74c2c4413223682d3b3217da8

This commit should fix the bug, if you can try for master branch (i just tried on simple project)
If it works for you i'll make a new bugfix release !
