### ISSUE TITLE
Fonts won't save properly in the project if using Make Link (Font)

### ISSUE THREAD

**Issue by LuisBurdallo** [samytichadou/FontSelector_blender_addon#9]
I am now having an even uglier issue. I change lots of fonts in my project, save and when I open it back the fonts revert back to the other one I had before.

I found that the cause is when using the function link font as trying to change a single font using your addon was kept just fine after restarting. So the root cause is “Make Link (Font)”

**Comment by samytichadou** [comment]
Solved with last commits
The relink revert should not be happening anymore.

And for the link function of blender, here’s the logic :
Blender will check on all automated Font Selector Action for “desync” fonts (changed by the users without using Font Selector) and try to resync them. If not possible, it will be displaid in the font selector panel of the object, letting the user directly correct it !

The action triggering the resync check :

- Blender startup
- Check for changes operator
- Refresh operator

I may also add a Only Resync operator here, but i’m not sure it is really needed, i don’t think these cases will happen a lot (losing the sync).
